CROSSBUILD:
  - 'scala-2.10'
  - 'scala-2.11'

CROSSBUILDAT:
  - 'scala-2.10'
  - 'scala-2.11'
  
ITSERVICES:
  - SPARK:
      image: stratio/spark:1.6.1
      env:
        - SPARK_MODE=master
  - ZOOKEEPER:
      image: stratio/zookeeper:3.4.6
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: elasticsearch:2.0.2
      sleep: 10
      env:
        - ES_JAVA_OPTS=-Des.cluster.name=%%JUID
  - SPARK:
      image: stratio/spark:1.6.1
      env:
        - SPARK_MODE=slave
        - SPARK_MASTER_HOST=%%SPARK#0
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:2.2.5.3
      sleep: 10
      env:
        - MAX_HEAP=256M
  - HADOOP:
      image: stratio/hadoop:2.7.2
      sleep: 10
      env:
        - MASTER=true
        - FUNC_MODE=hdfs
  - KAFKA:
      image: stratio/kafka:0.8.2.1
      env:
        - ZOOKEEPER_HOSTS=%%ZOOKEEPER:2181


ITPARAMETERS: >
    -Dcassandra.hosts.0=%%CASSANDRA
    -Dmongo.hosts.0=%%MONGODB
    -Delasticsearch.hosts.0=%%ELASTICSEARCH
    -Delasticsearch.cluster=%%JUID
    -Dspark.master=spark://%%SPARK:7077
    -Dhdfs.namenode=hdfs://%%HADOOP:8020
    -Dhdfs.user="Stratio"
    -Djars.externalJars="/root"
    -Dcatalog.zookeeper.connectionString=%%ZOOKEEPER:2181
    -Dstreaming.catalog.zookeeper.connectionString=%%ZOOKEEPER:2181
    -Dstreaming.receiver.kafka.connection=%%KAFKA:9092
    -Dstreaming.receiver.zookeeper.connectionString=%%ZOOKEEPER:2181
    -Dlauncher.sparkHome=/opt/sds/spark/

ATSERVICES:
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: elasticsearch:2.0.2
      sleep: 10
      env:
        - ES_JAVA_OPTS=-Des.cluster.name=%%JUID
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:2.2.5.3
      sleep: 10
      env:
        - MAX_HEAP=256M
  - CROSSDATA: 
      image: stratio/crossdata-%%CROSSBUILD:%%VERSION
      sleep: 10
      
ATPARAMETERS: >
    -DCROSSDATA_HOST=%%CROSSDATA:13420
    -DCASSANDRA_HOST=%%CASSANDRA
    -DCASSANDRA_CLUSTER="Stratio cluster"
    -DMONGO_HOST=%%MONGODB
    -DMONGO_PORT=27017
    -DES_NODE=%%ELASTICSEARCH
    -DES_PORT=9200
    -DES_NATIVE_PORT=9300
    -DES_CLUSTER=%%JUID
